### Home page
GET http://51.250.2.136/api/v1/home-page-content/
Accept: application/json

### Services
GET http://51.250.2.136/api/v1/services/
Accept: application/json

### GET Service_By_Id
GET http://51.250.2.136/api/v1/services/2
Accept: application/json
