FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_SITE_NAME
ARG API_URL
ARG NEXT_PUBLIC_IMAGE_HOST

ENV NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_IMAGE_HOST=$NEXT_PUBLIC_IMAGE_HOST

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]