FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_IMAGE_HOST
ARG NEXT_PUBLIC_API_URL
ARG API_URL


ENV NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME
ENV NEXT_PUBLIC_IMAGE_HOST=$NEXT_PUBLIC_IMAGE_HOST
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV API_URL=$API_URL

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]