import { FC } from 'react'
import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'

import '@app/styles/globals.scss'

import { mainMenu } from '@app/configs/main-menu.config'
import { drukWideCyrFont, manropeFont } from '@app/fonts'
import { RedirectAfterReload } from '@shared/ui/redirect-after-reload/RedirectAfterReload'
import { Header } from '@widgets/header'

export const metadata: Metadata = {
  title: 'Nextjs project',
  description: 'Generated by create next app'
}

const RootLayout: FC<React.PropsWithChildren & { modal: React.ReactNode }> = ({ children, modal }) => {
  return (
    <html lang="en">
      <body className={`${manropeFont.variable} ${drukWideCyrFont.variable}`}>
        <NextTopLoader color="#000000" shadow={false} showSpinner={false} />
        <Header menuList={mainMenu} />
        <main>{children}</main>
        {modal}
        <RedirectAfterReload />
      </body>
    </html>
  )
}

export default RootLayout
