import { FC, PropsWithChildren } from 'react'

import '@app/styles/globals.scss'
import clsx from 'clsx'
import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'

import { mainMenu } from '@app/configs/main-menu.config'
import { drukWideCyrFont, manropeFont } from '@app/fonts'

import { Header } from '@widgets/header'

export const metadata: Metadata = {
  title: 'Nextjs project',
  description: 'Generated by create next app'
}

const ServicesLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={clsx(`${manropeFont.variable} ${drukWideCyrFont.variable}`, 'bg')}>
        <NextTopLoader color="#000000" shadow={false} showSpinner={false} />
        <Header menuList={mainMenu} />
        <main>{children}</main>
      </body>
    </html>
  )
}
export default ServicesLayout
